# Load Boston Housing Dataset
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html#sklearn.datasets.load_boston

In [1]:
from sklearn.datasets import load_boston
house_data = load_boston()

In [12]:
# How many houses are there (N)
N = 0 #TBD
#DESCR', 'data', 'feature_names', 'filename', 'target']
len(house_data.data)

506

In [13]:
# A house has how many attributes(or features or signals or dimensions or columns)
n = 0 #TBD
len(house_data.feature_names)

# All attributes together make up a row (or input or x)

13

In [14]:
# Whats the Median value of the first house (target or label or output y)
house_data.target[0]

24.0

In [24]:
# Whats the value of feature RM (average number of rooms per dwelling) for the last house
print(house_data.data[-1,5])


6.03


#### House 8 all features
$
\begin{align}
X^{8} 
\end{align}
$


In [28]:
print(house_data.data[8])

[2.1124e-01 1.2500e+01 7.8700e+00 0.0000e+00 5.2400e-01 5.6310e+00
 1.0000e+02 6.0821e+00 5.0000e+00 3.1100e+02 1.5200e+01 3.8663e+02
 2.9930e+01]


#### House 8,  feature 2
(INDUS proportion of non-retail business acres per town)

$
\begin{align}
X_{2}^{8}
\end{align}
$


In [32]:
print(house_data.data[house_data.])

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


#### All houses feature 4
(NOX nitric oxides concentration)

$
\begin{align}
X_{4}
\end{align}
$


In [57]:
type(house_data.data[4])

numpy.ndarray

#### Target value for house 4
$
Y^{4}
$


In [38]:
print(house_data.target[4])

36.2


Small *x* and *y* are used to represent a *feature* and *target* of a single 

*   Elemento de lista

*   Elemento de lista 
*   Elemento de lista


*   Elemento de lista

house
#### Which among the following could be valid representation?
$
x^{4}\:, \: x_{2}\:,\:y^{4}\:,\:y_{2}
$

